---
#write here the item list(max allowed: infinite)
#example
item:
- "46"
- "259"
- "17:1"

#the radius of the explosion (min. 1, max 30)
explosion: 3

#turn on/off the plugin
status: "on"

#write here the world name where you want LuckyBlock works!
#set this field empty if you want that works on all worlds in the server
#if you want to apply only on two or more worlds, enter the names of the worlds separated by a comma
#example level: world, hungergames, lobby
level: []
...
